# Generated by Django 3.1.5 on 2021-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='projectComment',
        ),
    ]
