# Generated by Django 3.1.5 on 2021-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=13)),
                ('contactno', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=255)),
                ('more', models.TextField()),
            ],
        ),
    ]
