# Generated by Django 3.1.5 on 2021-03-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactno',
            new_name='phone',
        ),
    ]
